### ISSUE TITLE
License information missing from run_local_actions.sh

### ISSUE THREAD

**Issue by makermelissa** [adafruit/actions-ci-circuitpython-libs#10]
I'm now getting the following error on `pre-commit run --all-files`
```
# MISSING COPYRIGHT AND LICENSING INFORMATION

The following files have no copyright and licensing information:
* actions-ci/run_local_actions.sh
```

**Comment by caternuson** [comment]
welcome to the club?
https://github.com/adafruit/Adafruit_CircuitPython_MS8607/pull/4#issuecomment-702270993

**Comment by makermelissa** [comment]
Want to review my PR to fix this @caternuson?

**Comment by caternuson** [comment]
Looks OK. But I know pretty much nothing about the "reuse" stuff. Also not sure I understand why the CI is checking its own scripts? Seems unrelated to the repo code?

**Comment by makermelissa** [comment]
Thanks. It just checks everything by default. I think the point is to make updating licenses simpler instead of including a large block of text in each file.

**Comment by evaherrada** [comment]
Uh, so I just merged the PR without reading the issue and I'm not entirely sure if that was the right thing to do. Let me know and I can revert it.

**Comment by makermelissa** [comment]
It just needed a licensing block of text at the top. No functional changes.

**Comment by caternuson** [comment]
@dherrada Probably OK. It's just some text.

Should there be CI for the CI? Like something that runs here to make sure all the items here are OK?

**Comment by makermelissa** [comment]
Verified this is now fixed.

**Comment by makermelissa** [comment]
@caternuson yeah. There should probably be a test like pre-commit hooks that checks for the license info.

**Comment by caternuson** [comment]
Worked for me too. Thanks!
